# Use a imagem oficial do MySQL com a versão desejada
FROM mysql:latest

# Defina as variáveis de ambiente para configurar o MySQL
ENV MYSQL_ROOT_PASSWORD=HNj74PYaX7
ENV MYSQL_DATABASE=banco-grafwall-mysql
ENV MYSQL_USER=supervisor
ENV MYSQL_PASSWORD=jysOS9o8lB

COPY ./init.sql /docker-entrypoint-initdb.d/



# Exponha a porta do MySQL
EXPOSE 3307
     